tasks:
  - name: terraform
    init: |
      source ./bin/set_tf_alias
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
      cp .$PROJECT_ROOT/terraform.tfvars.example .$PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    init: |
      source ./bin/set_tf_alias
      source ./bin/install_aws_cli
    command: |
      # Run your AWS CLI commands here

  - name: http-server
    before: |
      npm install --global http-server
    command: |
      http-server
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform